sudo: false
language: node_js
node_js:
- stable
- '8'
- '6'
- '4'
matrix:
  fast_finish: true
branches:
  only:
    - master
    - /^greenkeeper-.*$/
notifications:
  email:
    on_success: never
cache:
  directories:
  - node_modules

before_script:
  - npm install typescript
  - npm run linter
script: 'npm run test'
after_script: 'npm run coverage'
